### ISSUE TITLE
How can I help?

### ISSUE THREAD

**Issue by infertux** [Galaxy-J5/android_kernel_samsung_j5nlte#1]
Hi @aapav01 & @CTXz,

I'm not sure if this is the best way to contact you so please let me know if there is a better channel.

First off, thank you very much for porting CM to the Galaxy J5. I recently bought this device and would love to run CM on it. I've never ported CM myself but have a bit of experience building CM from scratch.

I tried to build the recovery image from https://github.com/Galaxy-J5/android_device_samsung_j5nlte/tree/TWRP following instructions from https://wiki.cyanogenmod.org/w/Doc:_porting_intro#Then_build_a_test_recovery_image but `make` says the `recoveryimage` target isn't found. Is this supposed to work or are you still working on it?

I'm not using my device for anything critical yet so I'm happy to be a beta tester if you need someone to test your debug builds ;)

Thanks!

**Comment by infertux** [comment]
PS: It might be worth adding these repositories to https://wiki.cyanogenmod.org/w/Unofficial_Ports - looks like only the wiki admins can edit this page though...

**Comment by CTXz** [comment]
Negative, this isn't planning to be released on the cm unofficial ports list, atleast for now. XDA is the preferred choice for ROM listing where else the CM site is more of a additional feature option.

I'm not sure aapav wants his hangouts mentioned, but you can add me on hangouts under the following email : ctx.xda@gmail.com

**Comment by aapav01** [comment]
give me ur gmail id so we can add u there

**Comment by infertux** [comment]
Thanks for the reply and sorry about the delay. My Gmail ID is the same as my GitHub handle.

I followed the instructions from http://forum.xda-developers.com/android/development/recovery-twrp-2-8-7-0-samsung-galaxy-j5-t3219901 and got TWRP installed successfully.

Happy to test any alpha/beta build when the time is right. Thank you for your work on this.
